Repository AY2425S1-CS2103T-F09-2/tp, pull requests merged in 2024-11, with the labels that each got.

#165 Add UI for searchmode
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/contact/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, priority.Medium

#172 Fix consistent format for View command
  src/main/java/seedu/address/logic/commands/event/commands/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/event/parser/ViewEventCommandParser.java
  src/test/java/seedu/address/logic/commands/event/commands/ViewEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/event/parser/ViewEventCommandParserTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#181 Standardise naming of Find / Search / View commands
  docs/diagrams/LogicClassDiagram.puml
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/contact/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/contact/commands/FindRoleCommand.java
  src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/contact/parser/FindNameCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/parser/FindRoleCommandParser.java
  src/main/java/seedu/address/logic/parser/event/parser/FindEventCommandParser.java
  src/test/java/seedu/address/logic/commands/contact/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/commands/FindRoleCommandTest.java
  src/test/java/seedu/address/logic/commands/event/commands/FindEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/contact/parser/FindNameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/parser/FindRoleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/parser/FindEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/parser/ViewEventCommandParserTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#184 Clear command box after user enters a command even if invalid
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.Low, severity.Low, alpha-bug

#183 Update message usage for find-event command
  src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java
Labels: priority.High, severity.High, alpha-bug

#187 Exclude Persons from Search
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/CheckExcludedCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/ClearExcludedCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/ExcludePersonCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/ExitSearchModeCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExcludePersonCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/contact/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/searchmode/CheckExcludedCommandTest.java
  src/test/java/seedu/address/logic/commands/searchmode/ClearExcludedCommandTest.java
  src/test/java/seedu/address/logic/commands/searchmode/ExcludePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExcludePersonCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: type.Enhancement, type.Task, priority.Medium

#189 Specify Duplicated Field
  src/main/java/seedu/address/logic/commands/contact/commands/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/contact/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/contact/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, alpha-bug

#194 Display search keywords when searching by role
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/contact/commands/FindRoleCommand.java
  src/main/java/seedu/address/model/person/predicates/PersonIsRolePredicate.java
  src/test/java/seedu/address/logic/commands/contact/commands/FindRoleCommandTest.java
Labels: priority.Medium, severity.Low, alpha-bug

#199 Change searchmodesearch to throw ParseException on empty input and change success messages
  src/main/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommand.java
  src/main/java/seedu/address/logic/parser/SearchModeSearchCommandParser.java
  src/test/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchModeSearchCommandParserTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High, alpha-bug

#201 Misc UG change
  docs/UserGuide.md
Labels: type.Task

#207 Implement assigning multiple roles to a Person when editing
  src/main/java/seedu/address/logic/parser/contact/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/contact/parser/EditCommandParserTest.java
Labels: priority.High, severity.High, alpha-bug

#210 Improve constant abstractions
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/contact/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchModeSearchCommandParserTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/predicates/PersonIsRolePredicateTest.java
  src/test/java/seedu/address/model/role/RoleHandlerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRoleTest.java
Labels: priority.Medium, severity.Low, alpha-bug

#218 Error messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/ClearExcludedCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/ExcludePersonCommand.java
  src/main/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExcludePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParser.java
  src/test/java/seedu/address/logic/commands/searchmode/CheckExcludedCommandTest.java
  src/test/java/seedu/address/logic/commands/searchmode/ClearExcludedCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExcludePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParserTest.java
Labels: priority.High, severity.Medium, severity.High, alpha-bug

#225 Add testcase for Remove when related predicate
  src/test/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommandTest.java
Labels: type.Enhancement, priority.Medium, alpha-bug

#297 Adds Planned Enhancements to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#305 Makes removePersonFromEvent remove completely and fixes bug with index validation checking
  src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
  src/test/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommandTest.java
Labels: type.Bug, priority.High, severity.High

#314 Fill in missing search mode commands in User Guide
  docs/UserGuide.md
Labels: priority.Medium

#315 Change command name for adding event
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java
Labels: priority.Medium, severity.Low

#318 Fix tests for Person
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/TelegramUsernameTest.java
Labels: priority.Medium

#321 Widen remove error messages
  src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
Labels: priority.Medium, severity.Medium

#323 Improve event related tests
  src/test/java/seedu/address/model/event/EventListTest.java
  src/test/java/seedu/address/model/event/EventManagerTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#326 Update all parser tests to improve code coverage
  src/main/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/contact/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/parser/NewEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParserTest.java
Labels: priority.Medium

#334 Change Manual data editing warning to be in line with AB3
  docs/UserGuide.md
Labels: priority.High, severity.Medium, type.DocumentationBug

#340 Extend test coverage for entire codebase
  src/main/java/seedu/address/logic/commands/contact/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/ExcludePersonCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonInEventPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/TelegramUsernameTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/PersonIsRolePredicateTest.java
  src/test/java/seedu/address/model/predicates/PhoneNumberContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/predicates/TelegramContainsKeywordPredicateTest.java
Labels: priority.High

#346 Add planned enhancement on JSON handling
  docs/DeveloperGuide.md
Labels: type.Enhancement

#348 Add last tests
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium
